include $(NAVY_HOME)/Makefile.check

LIB_DIR ?= $(shell pwd)
INC_DIR += $(LIB_DIR)/include/
DST_DIR ?= $(LIB_DIR)/build/$(ISA)/
ARCHIVE ?= $(LIB_DIR)/build/$(NAME)-$(ISA).a

.DEFAULT_GOAL = archive

ifneq ($(ISA), native)
LIBS += libc
endif
INC_DIR += $(addsuffix /include/, $(addprefix $(NAVY_HOME)/libs/, $(LIBS)))

$(shell mkdir -p $(DST_DIR))

include $(NAVY_HOME)/Makefile.compile

archive: $(ARCHIVE)

$(ARCHIVE): $(OBJS)
	@echo + AR $@
	@ar rcs $(ARCHIVE) $(OBJS)

.PHONY: clean archive
clean: 
	rm -rf $(LIB_DIR)/build/
